//! # D-Bus interface proxy for: `org.gnome.Mutter.DisplayConfig`
//!
//! This code was generated by `zbus-xmlgen` `5.3.0` from D-Bus introspection data and adapted by hand.
//! Source: `mutter.xml`.
//!
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//!
//! [Writing a client proxy]: https://z-galaxy.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
//!
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use zbus::proxy;
use zbus::zvariant::OwnedValue;
use zbus::zvariant::Type;

pub type PropertyMap = HashMap<String, OwnedValue>;
pub type ApplyPropertyMap = HashMap<String, OwnedValue>;

#[derive(Debug, Clone, Serialize, Deserialize, Type, PartialEq, Eq, Hash)]
pub(crate) struct MonitorIdentity {
    pub(crate) connector: String,
    pub(crate) vendor: String,
    pub(crate) product: String,
    pub(crate) serial: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Type)]
pub(crate) struct Monitor {
    pub(crate) id: MonitorIdentity,
    pub(crate) modes: Vec<MonitorMode>,
    pub(crate) properties: PropertyMap,
}

#[derive(Debug, Clone, Serialize, Deserialize, Type)]
pub(crate) struct MonitorMode {
    pub(crate) id: String,
    pub(crate) width: i32,
    pub(crate) height: i32,
    pub(crate) refresh_rate: f64,
    pub(crate) preferred_scale: f64,
    pub(crate) supported_scales: Vec<f64>,
    pub(crate) properties: PropertyMap,
}

#[derive(Debug, Clone, Serialize, Deserialize, Type)]
pub(crate) struct LogicalMonitor {
    pub(crate) x: i32,
    pub(crate) y: i32,
    pub(crate) scale: f64,
    // TODO: use transform struct and implement from u32
    pub(crate) transform: u32,
    pub(crate) primary: bool,
    pub(crate) monitors: Vec<MonitorIdentity>,
    pub(crate) properties: PropertyMap,
}

#[derive(Debug, Clone, Serialize, Deserialize, Type)]
pub(crate) struct LogicalMonitorConfig {
    pub(crate) x: i32,
    pub(crate) y: i32,
    pub(crate) scale: f64,
    pub(crate) transform: u32,
    pub(crate) primary: bool,
    pub(crate) monitors: Vec<MonitorConfig>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Type)]
pub(crate) struct MonitorConfig {
    pub(crate) connector: String,
    pub(crate) id: String,
    pub(crate) properties: ApplyPropertyMap,
}

#[derive(Debug, Clone, Serialize, Deserialize, Type)]
pub(crate) struct CurrentState {
    pub(crate) serial: u32,
    pub(crate) monitors: Vec<Monitor>,
    pub(crate) logical_monitors: Vec<LogicalMonitor>,
    pub(crate) properties: PropertyMap,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Type)]
pub(crate) enum Method {
    Verify = 0,
    Temporary = 1,
    Persistent = 2,
}

#[proxy(
    interface = "org.gnome.Mutter.DisplayConfig",
    default_service = "org.gnome.Mutter.DisplayConfig",
    default_path = "/org/gnome/Mutter/DisplayConfig"
)]
pub trait DisplayConfig {
    /// GetCurrentState method
    fn get_current_state(&self) -> zbus::Result<CurrentState>;

    /// ApplyMonitorsConfig method
    fn apply_monitors_config(
        &self,
        serial: u32,
        method: Method,
        logical_monitors: &[LogicalMonitorConfig],
        properties: ApplyPropertyMap,
    ) -> zbus::Result<()>;

    /// MonitorsChanged signal
    #[zbus(signal)]
    fn monitors_changed(&self) -> zbus::Result<()>;

    /// ApplyMonitorsConfigAllowed property
    #[zbus(property)]
    fn apply_monitors_config_allowed(&self) -> zbus::Result<bool>;
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn current_state_signature_matches_xml() {
        assert_eq!(
            CurrentState::SIGNATURE.to_string(),
            "(ua((ssss)a(siiddada{sv})a{sv})a(iiduba(ssss)a{sv})a{sv})"
        );
    }

    #[test]
    fn logical_monitor_config_signature_matches_xml() {
        assert_eq!(
            LogicalMonitorConfig::SIGNATURE.to_string(),
            "(iiduba(ssa{sv}))"
        );
    }

    #[test]
    fn method_values_match_xml() {
        assert_eq!(Method::Verify as u32, 0);
        assert_eq!(Method::Temporary as u32, 1);
        assert_eq!(Method::Persistent as u32, 2);
    }

    #[test]
    fn method_signature_matches_xml() {
        assert_eq!(Method::SIGNATURE.to_string(), "u");
    }
}
