//! # D-Bus interface proxy for: `org.gnome.Mutter.DisplayConfig`
//!
//! This code was generated by `zbus-xmlgen` `5.3.0` from D-Bus introspection data and adapted by hand.
//! Source: `mutter.xml`.
//!
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//!
//! [Writing a client proxy]: https://z-galaxy.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
//!
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use zbus::proxy;
use zbus::zvariant::OwnedValue;
use zbus::zvariant::Type;

pub type PropertyMap = HashMap<String, OwnedValue>;
pub type ApplyPropertyMap = HashMap<String, OwnedValue>;

#[derive(Debug, Clone, Serialize, Deserialize, Type, PartialEq, Eq, Hash)]
struct MonitorIdentity {
    connector: String,
    vendor: String,
    product: String,
    serial: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Type)]
struct Monitor {
    id: MonitorIdentity,
    modes: Vec<MonitorMode>,
    properties: PropertyMap,
}

#[derive(Debug, Clone, Serialize, Deserialize, Type)]
struct MonitorMode {
    id: String,
    width: i32,
    height: i32,
    refresh_rate: f64,
    preferred_scale: f64,
    supported_scales: Vec<f64>,
    properties: PropertyMap,
}

#[derive(Debug, Clone, Serialize, Deserialize, Type)]
struct LogicalMonitor {
    x: i32,
    y: i32,
    scale: f64,
    // TODO: use transform struct and implement from u32
    transform: u32,
    primary: bool,
    monitors: Vec<MonitorConfig>,
    properties: PropertyMap,
}

#[derive(Debug, Clone, Serialize, Deserialize, Type)]
struct LogicalMonitorConfig {
    x: i32,
    y: i32,
    scale: f64,
    transform: u32,
    primary: bool,
    monitors: Vec<LogicalMonitorConfig>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Type)]
pub struct MonitorConfig {
    connector: String,
    id: String,
    properties: ApplyPropertyMap,
}

#[derive(Debug, Clone, Serialize, Deserialize, Type)]
struct CurrentState {
    serial: u32,
    monitors: Vec<Monitor>,
    logical_monitors: Vec<LogicalMonitor>,
    properties: PropertyMap,
}

#[derive(Debug, Clone, Serialize, Deserialize, Type)]
#[repr(u32)]
enum Method {
    Verify = 0,
    Temporary = 1,
    Persistent = 2,
}

#[proxy(interface = "org.gnome.Mutter.DisplayConfig", assume_defaults = true)]
pub trait DisplayConfig {
    /// GetCurrentState method
    #[allow(clippy::type_complexity)]
    #[allow(clippy::type_complexity)]
    fn get_current_state(&self) -> zbus::Result<CurrentState>;

    /// ApplyMonitorsConfig method
    #[allow(clippy::type_complexity)]
    fn apply_monitors_config(
        &self,
        serial: u32,
        method: Method,
        logical_monitors: &[LogicalMonitorConfig],
        properties: ApplyPropertyMap,
    ) -> zbus::Result<()>;

    /// MonitorsChanged signal
    #[zbus(signal)]
    fn monitors_changed(&self) -> zbus::Result<()>;

    /// ApplyMonitorsConfigAllowed property
    #[zbus(property)]
    fn apply_monitors_config_allowed(&self) -> zbus::Result<bool>;
}
